version: '2'
services:
  app: 
    build: 
      context: .
      dockerfile: Dockerfile
    command: yarn run application:watch
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    env_file:
      - .env
    environment: 
      - PORT=3001
  gateway:
    build: 
      context: .
      dockerfile: Dockerfile
    command: yarn run gateway:watch
    links:
      - app
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3002:3002"
    environment: 
      - CACHE_MAX_AGE=5
      - POLL_INTERVAL=30
      - PORT=3002
  test: 
    build: 
      context: .
      dockerfile: Dockerfile
    command: yarn run test
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    env_file:
      - .env
    depends_on: 
      - app
      - gateway